table '3. USD'
	lineageTag: 57479768-a786-4cb4-b91c-2a467da59407

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0ca4d9ff-622a-48f1-9c31-df8899529178
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 27e167ce-00c0-45a3-98db-46c293b8a458
			defaultHierarchy: LocalDateTable_083af31b-b129-4a13-9ea6-76d74dd1d287.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Close
		dataType: double
		lineageTag: 99933edc-a4e7-4ebc-9326-2bad0f63c3c6
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition '3. USD' = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://docs.google.com/spreadsheets/d/1VOATRWiNd6tHXjQwL6jE9_2Gm6U-xghIuwqvaDDaYcc/gviz/tq?tqx=out:csv&sheet=USD"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Close", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

